# Generated by Django 5.1.5 on 2025-04-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('deal_id', models.AutoField(primary_key=True, serialize=False)),
                ('deal_name', models.CharField(max_length=255)),
                ('pipeline', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('deal_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(max_length=50)),
                ('period', models.CharField(max_length=50)),
                ('period_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('expected_closingdate', models.DateField(blank=True, null=True)),
                ('follow_update', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('tags', models.CharField(blank=True, max_length=500, null=True)),
                ('priority', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'crm_deals',
            },
        ),
    ]
