# Generated by Django 5.1.5 on 2025-04-05 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_deals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deals',
            old_name='follow_update',
            new_name='follow_up_date',
        ),
    ]
