# Generated by Django 5.1.5 on 2025-04-05 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_rename_follow_update_deals_follow_up_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contacts',
            table='crm_contacts',
        ),
    ]
